package com.ex.ssm.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName product
 */
public class Product implements Serializable {

    /**
     * 主键，自增
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Long id;

    /**
     * 商品名称
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private String productName;

    /**
     * 图片
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private String image;

    /**
     * 标价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Long price;

    /**
     * 售价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Long salePrice;

    /**
     * 商品类型id
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Integer typeId;

    /**
     * 商品类型
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private String typeName;

    /**
     * 删除标记
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private String flag;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Date updateTime;

    /**
     * 创建商品的用户
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键，自增
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键，自增
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 商品名称
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public String getProductName() {
        return productName;
    }

    /**
     * 商品名称
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * 图片
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public String getImage() {
        return image;
    }

    /**
     * 图片
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * 标价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Long getPrice() {
        return price;
    }

    /**
     * 标价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * 售价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * 售价
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * 商品类型id
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * 商品类型id
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 商品类型
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * 商品类型
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * 删除标记
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public String getFlag() {
        return flag;
    }

    /**
     * 删除标记
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 创建商品的用户
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * 创建商品的用户
     *
     * @mbg.generated 2021-03-16 19:15:15
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", productName='" + productName + '\'' +
                ", image='" + image + '\'' +
                ", price=" + price +
                ", salePrice=" + salePrice +
                ", typeId=" + typeId +
                ", typeName='" + typeName + '\'' +
                ", flag='" + flag + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", createUser=" + createUser +
                '}';
    }
}
